CREATE DATABASE PersonalPasswordManager

use PersonalPasswordManager

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='PasswordManager')
BEGIN
	CREATE TABLE PasswordManager (
    PasswordManagerId INT IDENTITY(1,1) NOT NULL,
    Category VARCHAR(20),
    App NVARCHAR(20),
    UserName NVARCHAR(100) NULL,
    EncryptedPassword NVARCHAR(30) NULL,
    CreatedOn DATETIME NULL,
    ModifiedOn DATETIME NULL,
PRIMARY KEY CLUSTERED 
(
	[PasswordManagerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO


